### ISSUE TITLE
GPG Error - "gpg: no valid OpenPGP data found" during Debian/Ubuntu Install

### ISSUE THREAD

**Issue by mithlajkn** [sshlog/agent#10]
Description:
I encountered an issue while attempting to install the software on a Debian/Ubuntu system. During the installation process, I received the error message "gpg: no valid OpenPGP data found." This error seems to indicate that there is an issue with the OpenPGP data used in the installation process.

Steps to Reproduce:

Attempted installation on a Debian/Ubuntu system using the provided instructions.
Observed the error message "gpg: no valid OpenPGP data found."
Expected Behavior:
The installation should proceed without any errors, and the software should be successfully installed on the system.

Additional Information:

Operating System: Ubuntu 22.04.2 LTS
Kernel : 5.15.0-1042-azure
Architecture: x86-64
Installation method used: apt-get install

**Comment by matthill** [comment]
This should be resolved now -- the service hosting the apt repo was down.
